name: Setup & Dependencies

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Setup dependencies
      shell: bash
      run: |
        pnpm install

    - name: Prepare example env
      shell: bash
      run: |
        cp .env.example .env
